stages:
  - deploy
  - pages

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - npm run analyze
    - npm run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

update_elements:
  stage: deploy
  image: node:8.9.3
  before_script:
    - apt-get update && apt-get install -y openssh-client rsync && mkdir -p ~/.ssh && echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa && eval $(ssh-agent -s)
    - git config --local user.name "CatalystElements Bot"
    - git config --local user.email "catalystelementsbot@gitlab.wgtn.cat-it.co.nz"
    - git config --local push.default matching
  script:
    - ./scripts/ci-update-elements.sh
  only:
    - triggers
  tags:
    - docker
