stages:
  - deploy
  - pages

docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn install
    - yarn run analyze
    - yarn run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - triggers
  tags:
    - docker

auto_release:
  stage: deploy
  image: node:8.9.3
  before_script:
    # Set up ssh
    - mkdir -pvm 0700 ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && chmod 0600 ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa gitlab.wgtn.cat-it.co.nz > ~/.ssh/known_hosts
    - eval $(ssh-agent -s)

    # Set up git
    - git config --local --replace-all user.name "CatalystElements Bot"
    - git config --local --replace-all user.email "<>"
    - git config --local push.default simple
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git checkout $CATALYST_ELEMENTS_PIPELINE_REF
    - git reset --hard origin/$CATALYST_ELEMENTS_PIPELINE_REF
  script:
    - ./scripts/ci-update-elements.sh
  only:
    - triggers
  tags:
    - docker
