stages:
  - pages
  - deploy

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - npm run analyze
    - npm run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

update_elements:
  stage: pages
  image: node:8.9.3
  script:
    - yarn upgrade
    - git add .
    - git commit -m "CI Trigger - update_elements - [skip ci]"
    - git push
  only:
    - triggers
  tags:
    - docker
