stages:
  - deploy
  - pages

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - yarn run analyze
    - yarn run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

update_elements:
  stage: deploy
  image: node:8.9.3
  before_script:
    # - apt-get update && apt-get install -y openssh-client rsync && mkdir -p ~/.ssh && echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa && eval $(ssh-agent -s)
    # - git config --local user.name "CatalystElements Bot"
    # - git config --local user.email "catalystelementsbot@gitlab.wgtn.cat-it.co.nz"
    # - git config --local push.default simple

    - git config --local user.email $(git --no-pager show -s --format='%ae' HEAD)
    - git config --local user.name $(git --no-pager show -s --format='%an' HEAD)
    - git config --local push.default simple
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git checkout $CATALYST_ELEMENTS_PIPELINE_REF
    - git pull

    - apt-get update && apt-get install -y openssh-client rsync
    - mkdir -pvm 0700 ~/.ssh
    - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && chmod 0400 ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 0400 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)

    - echo "Change" > change.txt
  script:
    - ./scripts/ci-update-elements.sh
  only:
    - triggers
  tags:
    - docker
