stages:
  - deploy
  - pages

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - npm run analyze
    - npm run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

update_elements:
  stage: deploy
  image: node:8.9.3
  before_script:
    - apt-get update && apt-get install -y openssh-client rsync && mkdir -p ~/.ssh && echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa && eval $(ssh-agent -s)
  script:
    - echo "Test" > TestCI.txt
    - git add .
    - git commit -m "CI Trigger - update_elements - [skip ci]"
    - git push
  only:
    - triggers
  tags:
    - docker
